basePath: /api/v1
definitions:
  apperrors.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  dto.ActorInfo:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  dto.ExpectedActorUpdate:
    properties:
      dob:
        type: string
      gender:
        enum:
        - male
        - female
        - other
        type: string
      name:
        type: string
    type: object
  dto.ExpectedMovieUpdate:
    properties:
      description:
        type: string
      movie_actors:
        items:
          type: integer
        type: array
      rating:
        type: number
      release_date:
        type: string
      title:
        type: string
    type: object
  dto.JWT:
    properties:
      token:
        type: string
    type: object
  dto.LoginInfo:
    properties:
      login:
        type: string
      password:
        type: string
    type: object
  dto.MovieInfo:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  dto.NewActor:
    properties:
      dob:
        type: string
      gender:
        enum:
        - male
        - female
        - other
        type: string
      name:
        type: string
    type: object
  dto.NewMovie:
    properties:
      description:
        type: string
      movie_actors:
        items:
          type: integer
        type: array
      rating:
        type: number
      release_date:
        type: string
      title:
        type: string
    type: object
  entities.Actor:
    properties:
      actor_movies:
        items:
          $ref: '#/definitions/dto.MovieInfo'
        type: array
      dob:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  entities.Movie:
    properties:
      description:
        type: string
      id:
        type: integer
      movie_actors:
        items:
          $ref: '#/definitions/dto.ActorInfo'
        type: array
      rating:
        type: number
      release_date:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: lolwut-lol@yandex.ru
    name: Никита Архаров
    url: https://t.me/loomingsorrowdescent
  description: Бэкенд приложения "Фильмотека", который предоставляет REST API для
    управления базой данных фильмов.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: FlimLibrary Backend API
  version: "1.0"
paths:
  /actors/:
    get:
      description: Получить список всех актёров
      produces:
      - application/json
      responses:
        "200":
          description: Список актёров
          schema:
            items:
              $ref: '#/definitions/entities.Actor'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Получить список актёров
      tags:
      - Актёры
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные о новом актёре
        in: body
        name: actorData
        required: true
        schema:
          $ref: '#/definitions/dto.NewActor'
      produces:
      - application/json
      responses:
        "200":
          description: Объект нового актёра
          schema:
            $ref: '#/definitions/entities.Actor'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Создать актёра
      tags:
      - Актёры
  /actors/{id}/:
    delete:
      description: Удалить данные об актёре по его ID
      parameters:
      - description: ID актёра
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: no response
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Удалить данные об актёре
      tags:
      - Актёры
    get:
      description: Получить данные об актёре по его ID
      parameters:
      - description: ID актёра
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Объект актёра
          schema:
            $ref: '#/definitions/entities.Actor'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Получить данные об актёре
      tags:
      - Актёры
    patch:
      consumes:
      - application/json
      description: |-
        Изменить данные об актёре по его ID.
        Принимается любой набор параметров, но обязателен хотя бы один из них.
      parameters:
      - description: ID актёра
        in: path
        name: id
        required: true
        type: integer
      - description: Обновлённые данные актёра
        in: body
        name: actorData
        required: true
        schema:
          $ref: '#/definitions/dto.ExpectedActorUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Actor'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Изменить данные об актёре
      tags:
      - Актёры
  /auth/:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для авторизации
        in: body
        name: actorData
        required: true
        schema:
          $ref: '#/definitions/dto.LoginInfo'
      produces:
      - application/json
      responses:
        "200":
          description: 'JWT-токен для '
          schema:
            $ref: '#/definitions/dto.JWT'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Авторизоваться
      tags:
      - Авторизация
  /movies/:
    get:
      description: |-
        Получить список всех фильмов
        Если порядок сортировки не указан, для каждого типа есть порядок по умолчанию:
        Для названия и даты возрастающий, для рейтинга - убывающий
      parameters:
      - description: Тип сортировки (0 - название, 1 - рейтинг, 2 - дата выпуска)
        in: query
        name: sort
        required: true
        type: integer
      - description: Порядок сортировки (0 - возрастающий, 1 - убывающий)
        in: query
        name: order
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Список фильмов
          schema:
            items:
              $ref: '#/definitions/entities.Movie'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Получить список фильмов
      tags:
      - Фильмы
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные о новом фильме
        in: body
        name: movieData
        required: true
        schema:
          $ref: '#/definitions/dto.NewMovie'
      produces:
      - application/json
      responses:
        "200":
          description: Объект нового фильма
          schema:
            $ref: '#/definitions/entities.Movie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Создать фильм
      tags:
      - Фильмы
  /movies/{id}/:
    delete:
      description: Удалить данные об фильме по его ID
      parameters:
      - description: ID фильма
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: no response
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Удалить данные об фильме
      tags:
      - Фильмы
    get:
      description: Получить данные об фильме по его ID
      parameters:
      - description: ID фильма
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Объект фильма
          schema:
            $ref: '#/definitions/entities.Movie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Получить данные об фильме
      tags:
      - Фильмы
    patch:
      consumes:
      - application/json
      description: Изменить данные об фильме по его ID
      parameters:
      - description: ID фильма
        in: path
        name: id
        required: true
        type: integer
      - description: Обновлённые данные фильма
        in: body
        name: movieData
        required: true
        schema:
          $ref: '#/definitions/dto.ExpectedMovieUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Movie'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Изменить данные об фильме
      tags:
      - Фильмы
  /search/movie/:
    get:
      consumes:
      - application/json
      description: |-
        Поиск фильма по строке
        Строка ищется в названии фильма и списке актёров
      parameters:
      - description: Поисковый запрос
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Список результатов
          schema:
            items:
              $ref: '#/definitions/entities.Movie'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/apperrors.ErrorResponse'
      summary: Искать фильм
      tags:
      - Поиск
swagger: "2.0"
